INSERT INTO USER_ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('SYS_CODE', 'Code 및 System property 를 관리 할 수 있습니다.');
INSERT INTO USER_ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('SYS_ROLE', '권한 그룹을 관리 할 수 있습니다.');
INSERT INTO USER_ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('SYS_ACCOUNT', '사용자 및 계정을 관리 할 수 있습니다.');

INSERT INTO ROLE_GROUP (ROLE_GROUP_ID, ROLE_GROUP_NAME) VALUES (0, 'ADMIN');
INSERT INTO ROLE_GROUP (ROLE_GROUP_ID, ROLE_GROUP_NAME) VALUES (1, 'USER');

INSERT INTO GROUP_ROLES (ROLE_GROUP_ID, ROLE_NAME) VALUES (0, 'SYS_CODE');
INSERT INTO GROUP_ROLES (ROLE_GROUP_ID, ROLE_NAME) VALUES (0, 'SYS_ROLE');
INSERT INTO GROUP_ROLES (ROLE_GROUP_ID, ROLE_NAME) VALUES (0, 'SYS_ACCOUNT');

INSERT INTO ADMIN_USER (USER_NAME, DISPLAY_NAME, USER_PASSWORD, DT_CREATE, DT_UPDATE, USER_ENABLE, ROLE_GROUP_ID)
		VALUES ('test-user','test-user-name','{bcrypt}$2a$10$XlMeW.nhYnLvaTy1aIUYU.798RV/gddTaJHmtuLW03zx6gvL1cGqe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Y', 1);
-- 'test-admin','test-admin-name','test-admin-password', 'ADMIN'
INSERT INTO ADMIN_USER (USER_NAME, DISPLAY_NAME, USER_PASSWORD, DT_CREATE, DT_UPDATE, USER_ENABLE, ROLE_GROUP_ID)
		VALUES ('test-admin','test-admin-name','{bcrypt}$2a$10$atgQJwbdQ9kPZOCt5HpT/.UFSnQ63KGFCz2QLchKxwaUVhrl67ri.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Y', 0);

INSERT INTO PROPERTY (PROPERTY_KEY, PROPERTY_VALUE, PROPERTY_DESCRIPTION) VALUES( 'app.name', 'bigspoon', 'application name');

INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('100', '코드그룹1', '공통 코드 그룹 1 - 하위코드는 상위 코드에 붙여서 생성 하도록 하자', 'Y', NULL);
INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('101', '코드그룹2', '공통 코드 그룹 2', 'N', NULL);
INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('10001', '코드1-1', '공통 코드 그룹 1 의 코드1', 'Y', '100');
INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('10002', '코드1-2', '공통 코드 그룹 1 의 코드2', 'Y', '100');
INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('10101', '코드1-1', '공통 코드 그룹 1 의 코드1', 'Y', '101');
INSERT INTO COMMON_CODE (CODE, CODE_NAME, CODE_DESCRIPTION, YN_USE, PARENT_CODE) VALUES ('10102', '코드1-2', '공통 코드 그룹 1 의 코드2', 'N', '101');
